###############################################################################
# Security — External Secrets Operator Configuration
###############################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-secrets-manager-sa
  namespace: nexus-ksp
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/nexus-ksp-external-secrets-role"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: aws-secrets-manager-sa
            namespace: nexus-ksp
