"use client";
import React, { createContext, useState, useContext, useEffect } from 'react';

type Language = 'en' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    "NEXUS-KSP": "NEXUS-KSP",
    "Intelligence Platform": "Intelligence Platform",
    "Dashboard": "Dashboard",
    "Chat & Query": "Chat & Query",
    "Network Graph": "Network Graph",
    "Spatial Dispatch": "Spatial Dispatch",
    "Offender Profiles": "Offender Profiles",
    "Alerts": "Alerts",
    "Digital Forensics": "Digital Forensics",
    "Biometric Terminal": "Biometric Terminal",
    "Tactical Drone HUD": "Tactical Drone HUD",
    "Cyber Operations": "Cyber Operations",
    "Live Surveillance": "Live Surveillance",
    "SENTINEL PRE-CRIME": "SENTINEL PRE-CRIME",
    "Quantum Phenotyper": "Quantum Phenotyper",
    "Cellular Autopsy": "Cellular Autopsy",
    "Orbital Command": "Orbital Command",
    "Smart Grid C2": "Smart Grid C2",
    "Neural Extractor": "Neural Extractor",
    "Chronos Reconstruction": "Chronos Reconstruction",
    "Mecha Dispatch": "Mecha Dispatch",
    "Cybernetic Rehab": "Cybernetic Rehab",
    "Blockchain Vault": "Blockchain Vault",
    "Interrogation AI": "Interrogation AI",
    "Legal Drafter": "Legal Drafter",
    "Admin Control": "Admin Control",
    "English": "English",
    "Kannada": "ಕನ್ನಡ",
    "Language": "Language",
    "Command Center": "Command Center",
    "Karnataka State Police Intelligence Overview": "Karnataka State Police Intelligence Overview",
    "New AI Query": "New AI Query",
    "Active FIRs (24h)": "Active FIRs (24h)",
    "High Risk Accused": "High Risk Accused",
    "Emerging Hotspots": "Emerging Hotspots",
    "Active Alerts": "Active Alerts",
    "Critical": "Critical",
    "Live Crime Heatmap": "Live Crime Heatmap",
    "Interactive Map Loading...": "Interactive Map Loading...",
    "WebGL Context initializing": "WebGL Context initializing",
    "Recent Alerts": "Recent Alerts",
    "View All": "View All",
    "Hotspot Emerging": "Hotspot Emerging",
    "Unusual spike in two-wheeler thefts in Indiranagar.": "Unusual spike in two-wheeler thefts in Indiranagar.",
    "Repeat Offender Spotted": "Repeat Offender Spotted",
    "ACC-501 flagged near Yeshwanthpur station.": "ACC-501 flagged near Yeshwanthpur station.",
    "Syndicate Activity": "Syndicate Activity",
    "3 members of SYN-12 arrested.": "3 members of SYN-12 arrested.",
    "System Alerts": "System Alerts",
    "HIGH PRIORITY: Repeat Offender Detected": "HIGH PRIORITY: Repeat Offender Detected",
    "ACC-501 crossed district boundary into Bangalore Urban.": "ACC-501 crossed district boundary into Bangalore Urban.",
    "Spike in chain snatching incidents in Jayanagar.": "Spike in chain snatching incidents in Jayanagar.",
    "Hello, Investigator. I am the NEXUS-KSP AI. How can I assist you with your case today?": "Hello, Investigator. I am the NEXUS-KSP AI. How can I assist you with your case today?",
    "Based on the analysis, I found 3 linked cases. The primary accused is currently flagged as HIGH risk. [FIR-8821]": "Based on the analysis, I found 3 linked cases. The primary accused is currently flagged as HIGH risk. [FIR-8821]",
    "Analyzed network": "Analyzed network",
    "Queried financial DB": "Queried financial DB",
    "NEXUS AI Analyst": "NEXUS AI Analyst",
    "Session ID: 1993-29X": "Session ID: 1993-29X",
    "Export PDF": "Export PDF",
    "View Sources & Evidence": "View Sources & Evidence",
    "Sources:": "Sources:",
    "Citations:": "Citations:",
    "Evidence Chain:": "Evidence Chain:",
    "Analyzing across databases...": "Analyzing across databases...",
    "Ask about cases, offenders, hotspots...": "Ask about cases, offenders, hotspots...",
    "PROJECT SENTINEL": "PROJECT SENTINEL",
    "PRE-CRIME COGNITIVE PREDICTION MATRIX": "PRE-CRIME COGNITIVE PREDICTION MATRIX",
    "SYSTEM STATUS": "SYSTEM STATUS",
    "NEURAL NET ONLINE": "NEURAL NET ONLINE",
    "ACTIVE PRECOGS": "ACTIVE PRECOGS",
    "PREDICTED TARGET": "PREDICTED TARGET",
    "IDENTITY": "IDENTITY",
    "UNKNOWN_MALE_04": "UNKNOWN_MALE_04",
    "VECTOR": "VECTOR",
    "CLASS-1 FELONY (VIOLENT)": "CLASS-1 FELONY (VIOLENT)",
    "LOCATION": "LOCATION",
    "SECTOR 7G, INDIRANAGAR": "SECTOR 7G, INDIRANAGAR",
    "CRIME AVERTED": "CRIME AVERTED",
    "INTERCEPT TEAM DEPLOYED": "INTERCEPT TEAM DEPLOYED",
    "TIME TO EVENT": "TIME TO EVENT",
    "PROBABILITY": "PROBABILITY",
    "INITIATE INTERCEPT": "INITIATE INTERCEPT",
    "COGNITIVE METRICS": "COGNITIVE METRICS",
    "DOPAMINE DELTA": "DOPAMINE DELTA",
    "FINANCIAL STRESS": "FINANCIAL STRESS",
    "SOCIAL ISOLATION": "SOCIAL ISOLATION",
    "WEAPON PROXIMITY": "WEAPON PROXIMITY",
    "CONFIRMED": "CONFIRMED",
    "POWERED BY NEXUS PRE-CRIME ENGINE": "POWERED BY NEXUS PRE-CRIME ENGINE",
    "Isolating Genetic Material": "Isolating Genetic Material",
    "Quantum PCR Amplification": "Quantum PCR Amplification",
    "Mapping Chromosome 15 (Eye Color)": "Mapping Chromosome 15 (Eye Color)",
    "Analyzing Melanin Genotypes": "Analyzing Melanin Genotypes",
    "Synthesizing Craniofacial Structure": "Synthesizing Craniofacial Structure",
    "Rendering 3D Phenotype": "Rendering 3D Phenotype",
    "QUANTUM PHENOTYPER": "QUANTUM PHENOTYPER",
    "DNA TO FACIAL RECONSTRUCTION ALGORITHM": "DNA TO FACIAL RECONSTRUCTION ALGORITHM",
    "SYSTEM COHERENCE": "SYSTEM COHERENCE",
    "QUANTUM DECODING LOG": "QUANTUM DECODING LOG",
    "Processing...": "Processing...",
    "SYNTHESIS PROGRESS": "SYNTHESIS PROGRESS",
    "INSERT SAMPLE & SEQUENCE": "INSERT SAMPLE & SEQUENCE",
    "SYNTHESIS COMPLETE": "SYNTHESIS COMPLETE",
    "CONFIDENCE: 92.4% MATCH": "CONFIDENCE: 92.4% MATCH",
    "PHENOTYPIC TRAITS": "PHENOTYPIC TRAITS",
    "EYE COLOR": "EYE COLOR",
    "HAIR COLOR": "HAIR COLOR",
    "SKIN TONE": "SKIN TONE",
    "FACIAL MORPHOLOGY": "FACIAL MORPHOLOGY",
    "BROWN": "BROWN",
    "BLACK": "BLACK",
    "TYPE IV (MODERATE BROWN)": "TYPE IV (MODERATE BROWN)",
    "BROAD/ANGULAR": "BROAD/ANGULAR",
    "STANDBY": "STANDBY",
    "ORBITAL DROP INITIATED": "ORBITAL DROP INITIATED",
    "ATMOSPHERIC RE-ENTRY": "ATMOSPHERIC RE-ENTRY",
    "IMPACT IMMINENT": "IMPACT IMMINENT",
    "TOUCHDOWN: HEAVY MECHA ONLINE": "TOUCHDOWN: HEAVY MECHA ONLINE",
    "HEAVY MECHA DISPATCH": "HEAVY MECHA DISPATCH",
    "AUTONOMOUS RIOT CONTROL DIVISION": "AUTONOMOUS RIOT CONTROL DIVISION",
    "CHASSIS CONFIGURATION": "CHASSIS CONFIGURATION",
    "ARMOR RATING": "ARMOR RATING",
    "CLASS-4 TITANIUM ALLOY": "CLASS-4 TITANIUM ALLOY",
    "PRIMARY WEAPON": "PRIMARY WEAPON",
    "NON-LETHAL SONIC DISRUPTOR": "NON-LETHAL SONIC DISRUPTOR",
    "SECONDARY": "SECONDARY",
    "KINETIC FOAM LAUNCHER": "KINETIC FOAM LAUNCHER",
    "MECHA DEPLOYED": "MECHA DEPLOYED",
    "SECTOR SECURED. AWAITING COMMANDS.": "SECTOR SECURED. AWAITING COMMANDS.",
    "AUTHORIZE ORBITAL DROP": "AUTHORIZE ORBITAL DROP",
    "Blockchain Evidence Vault": "Blockchain Evidence Vault",
    "Cryptographic Immutable Ledger for Digital Evidence": "Cryptographic Immutable Ledger for Digital Evidence",
    "Current Ledger": "Current Ledger",
    "Search Hash or FIR...": "Search Hash or FIR...",
    "Multi-hop linkage analysis using Neo4j": "Multi-hop linkage analysis using Neo4j",
    "Co-offender Network": "Co-offender Network",
    "Financial Money Trail": "Financial Money Trail",
    "Profile": "Profile",
    "Status: Known Offender": "Status: Known Offender",
    "RISK SCORE": "RISK SCORE",
    "Deepfake Forensics Engine": "Deepfake Forensics Engine",
    "Real-Time Synthetic Audio & Voice Cloning Detection": "Real-Time Synthetic Audio & Voice Cloning Detection",
    "Biometric Identification Terminal": "Biometric Identification Terminal",
    "Cross-referencing facial landmarks against national criminal databases.": "Cross-referencing facial landmarks against national criminal databases.",
    "Predictive Spatial Dispatch": "Predictive Spatial Dispatch",
    "Real-time DBSCAN Hotspot Clustering & Dynamic Patrol Routing": "Real-time DBSCAN Hotspot Clustering & Dynamic Patrol Routing",
    "Update Matrix": "Update Matrix",
    "Auto-Dispatch Units": "Auto-Dispatch Units",
    "AI Target Overlay": "AI Target Overlay",
    "Displaying predicted crime geometries for Bangalore Central. Evaluated via Python Pattern Engine.": "Displaying predicted crime geometries for Bangalore Central. Evaluated via Python Pattern Engine.",
    "Active AI Hotspots": "Active AI Hotspots",
    "RISK": "RISK",
    "DISPATCH UNIT": "DISPATCH UNIT",
    "Fetching spatial matrix...": "Fetching spatial matrix...",
    "DRONE-01 : LIVE REC": "DRONE-01 : LIVE REC",
    "BATT": "BATT",
    "EST": "EST",
    "SIGNAL: STRONG": "SIGNAL: STRONG",
    "KSP AERIAL COMMAND": "KSP AERIAL COMMAND",
    "LAT:": "LAT:",
    "LNG:": "LNG:",
    "SYS TIME:": "SYS TIME:",
    "LOCK ACQUIRED": "LOCK ACQUIRED",
    "VEHICLE MATCH:": "VEHICLE MATCH:",
    "PL:": "PL:",
    "ALTITUDE": "ALTITUDE",
    "AIRSPEED": "AIRSPEED",
    "HDG": "HDG",
    "TACTICAL FEEDBACK": "TACTICAL FEEDBACK",
    "Target isolated within DBSCAN hotspot radius. Engaging auto-tracking mode. Ground units notified.": "Target isolated within DBSCAN hotspot radius. Engaging auto-tracking mode. Ground units notified.",
    "Scanning designated coordinates... Grid search active. Pattern Engine nominal.": "Scanning designated coordinates... Grid search active. Pattern Engine nominal.",
    "Global Cyber-Threat Operations": "Global Cyber-Threat Operations",
    "LIVE OSINT & DARK WEB MONITORING (CLASSIFIED)": "LIVE OSINT & DARK WEB MONITORING (CLASSIFIED)",
    "BLOCKED THREATS": "BLOCKED THREATS",
    "DEFCON LEVEL": "DEFCON LEVEL",
    "NODE STATUS": "NODE STATUS",
    "SECURE": "SECURE",
    "SENSOR ARRAY 04": "SENSOR ARRAY 04",
    "MONITORING BENGALURU METRO GRID": "MONITORING BENGALURU METRO GRID",
    "LIVE THREAT LOG": "LIVE THREAT LOG",
    "Automated LLM Legal Drafter": "Automated LLM Legal Drafter",
    "One-click generation of court-ready Warrants and Subpoenas via AI.": "One-click generation of court-ready Warrants and Subpoenas via AI.",
    "Draft Parameters": "Draft Parameters",
    "Target Suspect ID": "Target Suspect ID",
    "Case Type / Allegation": "Case Type / Allegation",
    "LLM DRAFTING...": "LLM DRAFTING...",
    "GENERATE WARRANT": "GENERATE WARRANT",
    "EXPORT TO PDF": "EXPORT TO PDF",
    "AWAITING AI DRAFT": "AWAITING AI DRAFT",
    "CELLULAR AUTOPSY": "CELLULAR AUTOPSY",
    "NANOBOT SWARM DIAGNOSTICS": "NANOBOT SWARM DIAGNOSTICS",
    "SUBJECT ID": "SUBJECT ID",
    "INJECT SWARM": "INJECT SWARM",
    "AWAITING INJECTION": "AWAITING INJECTION",
    "SYNTHETIC PATHOGEN DETECTED": "SYNTHETIC PATHOGEN DETECTED",
    "CAUSE OF DEATH: NANO-TOXICITY": "CAUSE OF DEATH: NANO-TOXICITY",
    "SWARM TELEMETRY": "SWARM TELEMETRY",
    "ACTIVE BOTS": "ACTIVE BOTS",
    "COVERAGE": "COVERAGE",
    "CELLULAR INTEGRITY": "CELLULAR INTEGRITY",
    "COMPROMISED": "COMPROMISED",
    "NOMINAL": "NOMINAL",
    "ANOMALY LOG": "ANOMALY LOG",
    "ORBITAL COMMAND": "ORBITAL COMMAND",
    "LEO SATELLITE UPLINK: SAT-V IND-01": "LEO SATELLITE UPLINK: SAT-V IND-01",
    "ALTITUDE: 400KM": "ALTITUDE: 400KM",
    "VELOCITY: 7.66 KM/S": "VELOCITY: 7.66 KM/S",
    "ENGAGE TARGET LOCK": "ENGAGE TARGET LOCK",
    "TRK: ACTIVE": "TRK: ACTIVE",
    "THERMAL ON": "THERMAL ON",
    "GYRO: STABLE": "GYRO: STABLE",
    "HIGH VALUE TARGET": "HIGH VALUE TARGET",
    "ISRO COMMAND LINK: ENCRYPTED": "ISRO COMMAND LINK: ENCRYPTED",
    "SMART GRID C2": "SMART GRID C2",
    "CITY-WIDE INFRASTRUCTURE OVERRIDE": "CITY-WIDE INFRASTRUCTURE OVERRIDE",
    "PROTOCOL: GHOST-NET": "PROTOCOL: GHOST-NET",
    "ACTIVE OVERRIDE": "ACTIVE OVERRIDE",
    "RELEASE GRID": "RELEASE GRID",
    "TACTICAL OVERRIDE ENGAGED": "TACTICAL OVERRIDE ENGAGED",
    "SMART INFRASTRUCTURE HIJACKED. SUSPECT CONTAINED.": "SMART INFRASTRUCTURE HIJACKED. SUSPECT CONTAINED.",
    "SELECT SECTOR FOR OVERRIDE": "SELECT SECTOR FOR OVERRIDE",
    "WARNING: THIS ACTION MANIPULATES PHYSICAL CITY INFRASTRUCTURE": "WARNING: THIS ACTION MANIPULATES PHYSICAL CITY INFRASTRUCTURE",
    "HIJACKED": "HIJACKED",
    "Policy & Audit Control Panel": "Policy & Audit Control Panel",
    "Configure security layers, audit trails, and automated thresholds": "Configure security layers, audit trails, and automated thresholds",
    "Refresh State": "Refresh State",
    "Cryptographic Audit Trail": "Cryptographic Audit Trail",
    "Alert Rule Policies": "Alert Rule Policies",
    "Role Access Control": "Role Access Control",
    "Tamper Simulator": "Tamper Simulator",
    "Tamper-Proof Audit logs": "Tamper-Proof Audit logs",
    "SHA-256 Validation Active": "SHA-256 Validation Active",
    "Timestamp": "Timestamp",
    "User": "User",
    "Action": "Action",
    "IP Address": "IP Address",
    "Query Details": "Query Details",
    "Cryptographic Integrity": "Cryptographic Integrity",
    "TAMPERED / INVALID SIGNATURE": "TAMPERED / INVALID SIGNATURE",
    "VERIFIED HASH": "VERIFIED HASH",
    "Define New Alert Threshold": "Define New Alert Threshold",
    "Rule Type": "Rule Type",
    "Condition Expression": "Condition Expression",
    "Add Rule to Alert Engine": "Add Rule to Alert Engine",
    "Active System Monitoring Rules": "Active System Monitoring Rules",
    "ACTIVE MONITORING": "ACTIVE MONITORING",
    "Map Officer Role": "Map Officer Role",
    "Officer Email": "Officer Email",
    "RBAC Role": "RBAC Role",
    "Division / Unit": "Division / Unit",
    "Assign Role": "Assign Role",
    "Keycloak Mapped Officers & Roles": "Keycloak Mapped Officers & Roles",
    "Assigned Role": "Assigned Role",
    "Division": "Division",
    "Actions": "Actions",
    "Cryptographic Tamper Simulator": "Cryptographic Tamper Simulator",
    "Every query executed on the NEXUS-KSP engine computes a strict SHA-256 HMAC of the (query + response payload), signed at the database interface. If any record is mutated by a hacker or rogue script directly inside the database, the signature verification check will fail.": "Every query executed on the NEXUS-KSP engine computes a strict SHA-256 HMAC of the (query + response payload), signed at the database interface. If any record is mutated by a hacker or rogue script directly inside the database, the signature verification check will fail.",
    "Click below to inject simulated database corruption to show how the audit trail catches mutations in real-time.": "Click below to inject simulated database corruption to show how the audit trail catches mutations in real-time.",
    "Reset Logs (Fix Database Integrity)": "Reset Logs (Fix Database Integrity)",
    "Simulate Database SQL Mutation (Tampering)": "Simulate Database SQL Mutation (Tampering)",
    "CRITICAL SYSTEM THREAT:": "CRITICAL SYSTEM THREAT:",
    "A query in Row #1 was altered in the Postgres logs, but its SHA-256 integrity hash remains mismatched. The audit engine flagged this mutation instantly!": "A query in Row #1 was altered in the Postgres logs, but its SHA-256 integrity hash remains mismatched. The audit engine flagged this mutation instantly!",
    "AI Suspect Interrogation Simulator": "AI Suspect Interrogation Simulator",
    "PSYCHOLOGICAL AVATAR MODULE: ACC-8091 (Ravi Kumar)": "PSYCHOLOGICAL AVATAR MODULE: ACC-8091 (Ravi Kumar)",
    "AVATAR STATUS": "AVATAR STATUS",
    "AGGRESSION THRESHOLD: HIGH": "AGGRESSION THRESHOLD: HIGH",
    "INTERROGATION TRANSCRIPT": "INTERROGATION TRANSCRIPT",
    "INITIATE QUESTIONING SEQUENCE": "INITIATE QUESTIONING SEQUENCE",
    "INVESTIGATOR": "INVESTIGATOR",
    "SUSPECT AVATAR": "SUSPECT AVATAR",
    "Analyzing psychological parameters...": "Analyzing psychological parameters...",
    "INTERROGATE": "INTERROGATE",
    "BIOMETRIC TELEMETRY": "BIOMETRIC TELEMETRY",
    "CORTISOL / STRESS": "CORTISOL / STRESS",
    "DECEPTION PROBABILITY": "DECEPTION PROBABILITY",
    "VOCAL TENSION FREQUENCY": "VOCAL TENSION FREQUENCY",
    "CYBERNETIC REHABILITATION": "CYBERNETIC REHABILITATION",
    "NEURAL PATHWAY OVERWRITE PROTOCOL": "NEURAL PATHWAY OVERWRITE PROTOCOL",
    "RECIDIVISM PROBABILITY": "RECIDIVISM PROBABILITY",
    "SUBJECT REHABILITATED": "SUBJECT REHABILITATED",
    "SOCIETAL REINTEGRATION APPROVED": "SOCIETAL REINTEGRATION APPROVED",
    "TARGET PATHWAYS": "TARGET PATHWAYS",
    "SYNTHETIC OVERRIDE": "SYNTHETIC OVERRIDE",
    "NATURAL (HOSTILE)": "NATURAL (HOSTILE)",
    "OVERWRITING [": "OVERWRITING [",
    "SEQUENCE COMPLETE": "SEQUENCE COMPLETE",
    "COMMENCE NEURAL REWRITE": "COMMENCE NEURAL REWRITE",
    "CHRONOS MODULE": "CHRONOS MODULE",
    "AMBIENT TEMPORAL RECONSTRUCTION": "AMBIENT TEMPORAL RECONSTRUCTION",
    "SCENE LOCK: SECTOR 4": "SCENE LOCK: SECTOR 4",
    "T-MINUS:": "T-MINUS:",
    "SECONDS": "SECONDS",
    "T-MINUS 100s": "T-MINUS 100s",
    "CURRENT:": "CURRENT:",
    "EVENT START (0s)": "EVENT START (0s)",
    "Real-Time AI Surveillance": "Real-Time AI Surveillance",
    "Automated Object Tracking & Anomaly Detection": "Automated Object Tracking & Anomaly Detection",
    "SYSTEM ACTIVE": "SYSTEM ACTIVE",
    "ANOMALY DETECTIONS": "ANOMALY DETECTIONS",
    "Monitoring feeds...": "Monitoring feeds..."
  },
  kn: {
    "NEXUS-KSP": "ನೆಕ್ಸಸ್-ಕೆಎಸ್ಪಿ",
    "Intelligence Platform": "ಗುಪ್ತಚರ ವೇದಿಕೆ",
    "Dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "Chat & Query": "ಚಾಟ್ ಮತ್ತು ಪ್ರಶ್ನೆ",
    "Network Graph": "ನೆಟ್‌ವರ್ಕ್ ಗ್ರಾಫ್",
    "Spatial Dispatch": "ಪ್ರಾದೇಶಿಕ ರವಾನೆ",
    "Offender Profiles": "ಅಪರಾಧಿಗಳ ಪ್ರೊಫೈಲ್‌ಗಳು",
    "Alerts": "ಎಚ್ಚರಿಕೆಗಳು",
    "Digital Forensics": "ಡಿಜಿಟಲ್ ಫೋರೆನ್ಸಿಕ್ಸ್",
    "Biometric Terminal": "ಬಯೋಮೆಟ್ರಿಕ್ ಟರ್ಮಿನಲ್",
    "Tactical Drone HUD": "ಯುದ್ಧತಂತ್ರದ ಡ್ರೋನ್ HUD",
    "Cyber Operations": "ಸೈಬರ್ ಕಾರ್ಯಾಚರಣೆಗಳು",
    "Live Surveillance": "ನೇರ ಕಣ್ಗಾವಲು",
    "SENTINEL PRE-CRIME": "ಸೆಂಟಿನೆಲ್ ಪೂರ್ವ-ಅಪರಾಧ",
    "Quantum Phenotyper": "ಕ್ವಾಂಟಮ್ ಫಿನೋಟೈಪರ್",
    "Cellular Autopsy": "ಸೆಲ್ಯುಲಾರ್ ಶವಪರೀಕ್ಷೆ",
    "Orbital Command": "ಕಕ್ಷೆಯ ಕಮಾಂಡ್",
    "Smart Grid C2": "ಸ್ಮಾರ್ಟ್ ಗ್ರಿಡ್ C2",
    "Neural Extractor": "ನ್ಯೂರಲ್ ಎಕ್ಸ್‌ಟ್ರಾಕ್ಟರ್",
    "Chronos Reconstruction": "ಕ್ರೊನೊಸ್ ಪುನರ್ನಿರ್ಮಾಣ",
    "Mecha Dispatch": "ಮೆಕಾ ಡಿಸ್ಪ್ಯಾಚ್",
    "Cybernetic Rehab": "ಸೈಬರ್ನೆಟಿಕ್ ರಿಹ್ಯಾಬ್",
    "Blockchain Vault": "ಬ್ಲಾಕ್‌ಚೈನ್ ವಾಲ್ಟ್",
    "Interrogation AI": "ವಿಚಾರಣೆ AI",
    "Legal Drafter": "ಕಾನೂನು ಕರಡುಗಾರ",
    "Admin Control": "ನಿರ್ವಾಹಕ ನಿಯಂತ್ರಣ",
    "English": "English",
    "Kannada": "ಕನ್ನಡ",
    "Language": "ಭಾಷೆ",
    "Command Center": "ಕಮಾಂಡ್ ಸೆಂಟರ್",
    "Karnataka State Police Intelligence Overview": "ಕರ್ನಾಟಕ ರಾಜ್ಯ ಪೊಲೀಸ್ ಗುಪ್ತಚರ ಅವಲೋಕನ",
    "New AI Query": "ಹೊಸ AI ಪ್ರಶ್ನೆ",
    "Active FIRs (24h)": "ಸಕ್ರಿಯ FIR ಗಳು (24ಗಂ)",
    "High Risk Accused": "ಹೆಚ್ಚಿನ ಅಪಾಯದ ಆರೋಪಿಗಳು",
    "Emerging Hotspots": "ಹೊಸ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು",
    "Active Alerts": "ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು",
    "Critical": "ಗಂಭೀರ",
    "Live Crime Heatmap": "ಲೈವ್ ಕ್ರೈಮ್ ಹೀಟ್‌ಮ್ಯಾಪ್",
    "Interactive Map Loading...": "ಸಂವಾದಾತ್ಮಕ ನಕ್ಷೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "WebGL Context initializing": "WebGL ಕಾನ್ಟೆಕ್ಸ್ಟ್ ಪ್ರಾರಂಭವಾಗುತ್ತಿದೆ",
    "Recent Alerts": "ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು",
    "View All": "ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ",
    "Hotspot Emerging": "ಹೊಸ ಹಾಟ್‌ಸ್ಪಾಟ್",
    "Unusual spike in two-wheeler thefts in Indiranagar.": "ಇಂದಿರಾನಗರದಲ್ಲಿ ದ್ವಿಚಕ್ರ ವಾಹನ ಕಳ್ಳತನದಲ್ಲಿ ಅಸಾಮಾನ್ಯ ಏರಿಕೆ.",
    "Repeat Offender Spotted": "ಪುನರಾವರ್ತಿತ ಅಪರಾಧಿ ಪತ್ತೆಯಾಗಿದ್ದಾನೆ",
    "ACC-501 flagged near Yeshwanthpur station.": "ಯಶವಂತಪುರ ನಿಲ್ದಾಣದ ಬಳಿ ACC-501 ಪತ್ತೆಯಾಗಿದೆ.",
    "Syndicate Activity": "ಸಿಂಡಿಕೇಟ್ ಚಟುವಟಿಕೆ",
    "3 members of SYN-12 arrested.": "SYN-12 ರ 3 ಸದಸ್ಯರನ್ನು ಬಂಧಿಸಲಾಗಿದೆ.",
    "System Alerts": "ಸಿಸ್ಟಮ್ ಎಚ್ಚರಿಕೆಗಳು",
    "HIGH PRIORITY: Repeat Offender Detected": "ಹೆಚ್ಚಿನ ಆದ್ಯತೆ: ಪುನರಾವರ್ತಿತ ಅಪರಾಧಿ ಪತ್ತೆಯಾಗಿದ್ದಾನೆ",
    "ACC-501 crossed district boundary into Bangalore Urban.": "ACC-501 ಜಿಲ್ಲಾ ಗಡಿಯನ್ನು ದಾಟಿ ಬೆಂಗಳೂರು ನಗರವನ್ನು ಪ್ರವೇಶಿಸಿದೆ.",
    "Spike in chain snatching incidents in Jayanagar.": "ಜಯನಗರದಲ್ಲಿ ಚೈನ್ ಕಸಿಯುವ ಘಟನೆಗಳಲ್ಲಿ ಏರಿಕೆ.",
    "Hello, Investigator. I am the NEXUS-KSP AI. How can I assist you with your case today?": "ನಮಸ್ಕಾರ ತನಿಖಾಧಿಕಾರಿ. ನಾನು NEXUS-KSP AI. ಇಂದು ನಿಮ್ಮ ಪ್ರಕರಣದಲ್ಲಿ ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?",
    "Based on the analysis, I found 3 linked cases. The primary accused is currently flagged as HIGH risk. [FIR-8821]": "ವಿಶ್ಲೇಷಣೆಯ ಆಧಾರದ ಮೇಲೆ, ನಾನು 3 ಸಂಬಂಧಿತ ಪ್ರಕರಣಗಳನ್ನು ಕಂಡುಕೊಂಡಿದ್ದೇನೆ. ಪ್ರಾಥಮಿಕ ಆರೋಪಿಯನ್ನು ಪ್ರಸ್ತುತ ಹೆಚ್ಚಿನ ಅಪಾಯವೆಂದು ಗುರುತಿಸಲಾಗಿದೆ. [FIR-8821]",
    "Analyzed network": "ನೆಟ್‌ವರ್ಕ್ ವಿಶ್ಲೇಷಿಸಲಾಗಿದೆ",
    "Queried financial DB": "ಹಣಕಾಸು ಡೇಟಾಬೇಸ್ ಪ್ರಶ್ನಿಸಲಾಗಿದೆ",
    "NEXUS AI Analyst": "ನೆಕ್ಸಸ್ AI ವಿಶ್ಲೇಷಕ",
    "Session ID: 1993-29X": "ಸೆಷನ್ ಐಡಿ: 1993-29X",
    "Export PDF": "ಪಿಡಿಎಫ್ ರಫ್ತು ಮಾಡಿ",
    "View Sources & Evidence": "ಮೂಲಗಳು ಮತ್ತು ಪುರಾವೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
    "Sources:": "ಮೂಲಗಳು:",
    "Citations:": "ಉಲ್ಲೇಖಗಳು:",
    "Evidence Chain:": "ಸಾಕ್ಷ್ಯ ಸರಣಿ:",
    "Analyzing across databases...": "ಡೇಟಾಬೇಸ್‌ಗಳಾದ್ಯಂತ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    "Ask about cases, offenders, hotspots...": "ಪ್ರಕರಣಗಳು, ಅಪರಾಧಿಗಳು, ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    "PROJECT SENTINEL": "ಪ್ರಾಜೆಕ್ಟ್ ಸೆಂಟಿನೆಲ್",
    "PRE-CRIME COGNITIVE PREDICTION MATRIX": "ಪೂರ್ವ-ಅಪರಾಧ ಅರಿವಿನ ಮುನ್ಸೂಚನೆ ಮ್ಯಾಟ್ರಿಕ್ಸ್",
    "SYSTEM STATUS": "ಸಿಸ್ಟಮ್ ಸ್ಥಿತಿ",
    "NEURAL NET ONLINE": "ನ್ಯೂರಲ್ ನೆಟ್ ಆನ್‌ಲೈನ್",
    "ACTIVE PRECOGS": "ಸಕ್ರಿಯ ಪ್ರಿಕಾಗ್ಸ್",
    "PREDICTED TARGET": "ಊಹಿಸಲಾದ ಗುರಿ",
    "IDENTITY": "ಗುರುತು",
    "UNKNOWN_MALE_04": "UNKNOWN_MALE_04",
    "VECTOR": "ವೆಕ್ಟರ್",
    "CLASS-1 FELONY (VIOLENT)": "CLASS-1 ಫೆಲೋನಿ (ಹಿಂಸಾತ್ಮಕ)",
    "LOCATION": "ಸ್ಥಳ",
    "SECTOR 7G, INDIRANAGAR": "SECTOR 7G, INDIRANAGAR",
    "CRIME AVERTED": "ಅಪರಾಧವನ್ನು ತಡೆಯಲಾಗಿದೆ",
    "INTERCEPT TEAM DEPLOYED": "ಇಂಟರ್ಸೆಪ್ಟ್ ತಂಡವನ್ನು ನಿಯೋಜಿಸಲಾಗಿದೆ",
    "TIME TO EVENT": "ಘಟನೆಗೆ ಸಮಯ",
    "PROBABILITY": "ಸಂಭವನೀಯತೆ",
    "INITIATE INTERCEPT": "ಇಂಟರ್ಸೆಪ್ಟ್ ಪ್ರಾರಂಭಿಸಿ",
    "COGNITIVE METRICS": "ಅರಿವಿನ ಮೆಟ್ರಿಕ್ಸ್",
    "DOPAMINE DELTA": "ಡೋಪಮೈನ್ ಡೆಲ್ಟಾ",
    "FINANCIAL STRESS": "ಹಣಕಾಸಿನ ಒತ್ತಡ",
    "SOCIAL ISOLATION": "ಸಾಮಾಜಿಕ ಪ್ರತ್ಯೇಕತೆ",
    "WEAPON PROXIMITY": "ಆಯುಧ ಸಾಮೀಪ್ಯ",
    "CONFIRMED": "ದೃಢಪಡಿಸಲಾಗಿದೆ",
    "POWERED BY NEXUS PRE-CRIME ENGINE": "ನೆಕ್ಸಸ್ ಪ್ರಿ-ಕ್ರೈಮ್ ಎಂಜಿನ್‌ನಿಂದ ನಡೆಸಲ್ಪಡುತ್ತಿದೆ",
    "Isolating Genetic Material": "ಆನುವಂಶಿಕ ವಸ್ತುಗಳನ್ನು ಪ್ರತ್ಯೇಕಿಸುವುದು",
    "Quantum PCR Amplification": "ಕ್ವಾಂಟಮ್ ಪಿಸಿಆರ್ ವರ್ಧನೆ",
    "Mapping Chromosome 15 (Eye Color)": "ಕ್ರೋಮೋಸೋಮ್ 15 ಅನ್ನು ಮ್ಯಾಪಿಂಗ್ ಮಾಡಲಾಗುತ್ತಿದೆ (ಕಣ್ಣಿನ ಬಣ್ಣ)",
    "Analyzing Melanin Genotypes": "ಮೆಲನಿನ್ ಜಿನೋಟೈಪ್‌ಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ",
    "Synthesizing Craniofacial Structure": "ಕ್ರೇನಿಯೊಫೇಶಿಯಲ್ ರಚನೆಯನ್ನು ಸಂಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ",
    "Rendering 3D Phenotype": "3D ಫಿನೋಟೈಪ್ ಅನ್ನು ರೆಂಡರಿಂಗ್ ಮಾಡಲಾಗುತ್ತಿದೆ",
    "QUANTUM PHENOTYPER": "ಕ್ವಾಂಟಮ್ ಫಿನೋಟೈಪರ್",
    "DNA TO FACIAL RECONSTRUCTION ALGORITHM": "ಡಿಎನ್ಎಯಿಂದ ಮುಖದ ಮರುನಿರ್ಮಾಣ ಅಲ್ಗಾರಿದಮ್",
    "SYSTEM COHERENCE": "ಸಿಸ್ಟಮ್ ಸುಸಂಬದ್ಧತೆ",
    "QUANTUM DECODING LOG": "ಕ್ವಾಂಟಮ್ ಡಿಕೋಡಿಂಗ್ ಲಾಗ್",
    "Processing...": "ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    "SYNTHESIS PROGRESS": "ಸಂಶ್ಲೇಷಣೆ ಪ್ರಗತಿ",
    "INSERT SAMPLE & SEQUENCE": "ಮಾದರಿಯನ್ನು ಸೇರಿಸಿ ಮತ್ತು ಅನುಕ್ರಮಗೊಳಿಸಿ",
    "SYNTHESIS COMPLETE": "ಸಂಶ್ಲೇಷಣೆ ಪೂರ್ಣಗೊಂಡಿದೆ",
    "CONFIDENCE: 92.4% MATCH": "ವಿಶ್ವಾಸ: 92.4% ಹೊಂದಾಣಿಕೆ",
    "PHENOTYPIC TRAITS": "ಫಿನೋಟೈಪಿಕ್ ಗುಣಲಕ್ಷಣಗಳು",
    "EYE COLOR": "ಕಣ್ಣಿನ ಬಣ್ಣ",
    "HAIR COLOR": "ಕೂದಲಿನ ಬಣ್ಣ",
    "SKIN TONE": "ಚರ್ಮದ ಬಣ್ಣ",
    "FACIAL MORPHOLOGY": "ಮುಖದ ರೂಪವಿಜ್ಞಾನ",
    "BROWN": "ಕಂದು",
    "BLACK": "ಕಪ್ಪು",
    "TYPE IV (MODERATE BROWN)": "ವಿಧ IV (ಮಧ್ಯಮ ಕಂದು)",
    "BROAD/ANGULAR": "ವಿಶಾಲ/ಕೋನೀಯ",
    "STANDBY": "ಸ್ಟ್ಯಾಂಡ್‌ಬೈ",
    "ORBITAL DROP INITIATED": "ಆರ್ಬಿಟಲ್ ಡ್ರಾಪ್ ಪ್ರಾರಂಭಿಸಲಾಗಿದೆ",
    "ATMOSPHERIC RE-ENTRY": "ವಾತಾವರಣದ ಮರು-ಪ್ರವೇಶ",
    "IMPACT IMMINENT": "ಪರಿಣಾಮ ಸನ್ನಿಹಿತವಾಗಿದೆ",
    "TOUCHDOWN: HEAVY MECHA ONLINE": "ಟಚ್‌ಡೌನ್: ಹೆವಿ ಮೆಚಾ ಆನ್‌ಲೈನ್",
    "HEAVY MECHA DISPATCH": "ಹೆವಿ ಮೆಚಾ ಡಿಸ್ಪ್ಯಾಚ್",
    "AUTONOMOUS RIOT CONTROL DIVISION": "ಸ್ವಾಯತ್ತ ಗಲಭೆ ನಿಯಂತ್ರಣ ವಿಭಾಗ",
    "CHASSIS CONFIGURATION": "ಚಾಸಿಸ್ ಕಾನ್ಫಿಗರೇಶನ್",
    "ARMOR RATING": "ಆರ್ಮರ್ ರೇಟಿಂಗ್",
    "CLASS-4 TITANIUM ALLOY": "ಕ್ಲಾಸ್-4 ಟೈಟಾನಿಯಂ ಮಿಶ್ರಲೋಹ",
    "PRIMARY WEAPON": "ಪ್ರಾಥಮಿಕ ಆಯುಧ",
    "NON-LETHAL SONIC DISRUPTOR": "ಮಾರಣಾಂತಿಕವಲ್ಲದ ಸೋನಿಕ್ ಡಿಸ್ರಪ್ಟರ್",
    "SECONDARY": "ದ್ವಿತೀಯ",
    "KINETIC FOAM LAUNCHER": "ಕೈನೆಟಿಕ್ ಫೋಮ್ ಲಾಂಚರ್",
    "MECHA DEPLOYED": "ಮೆಕಾ ನಿಯೋಜಿಸಲಾಗಿದೆ",
    "SECTOR SECURED. AWAITING COMMANDS.": "ವಲಯವನ್ನು ಭದ್ರಪಡಿಸಲಾಗಿದೆ. ಆಜ್ಞೆಗಳಿಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ.",
    "AUTHORIZE ORBITAL DROP": "ಆರ್ಬಿಟಲ್ ಡ್ರಾಪ್ ಅಧಿಕೃತಗೊಳಿಸಿ",
    "Blockchain Evidence Vault": "ಬ್ಲಾಕ್‌ಚೈನ್ ಎವಿಡೆನ್ಸ್ ವಾಲ್ಟ್",
    "Cryptographic Immutable Ledger for Digital Evidence": "ಡಿಜಿಟಲ್ ಸಾಕ್ಷ್ಯಗಳಿಗಾಗಿ ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಇಮ್ಯುಟಬಲ್ ಲೆಡ್ಜರ್",
    "Current Ledger": "ಪ್ರಸ್ತುತ ಲೆಡ್ಜರ್",
    "Search Hash or FIR...": "ಹ್ಯಾಶ್ ಅಥವಾ ಎಫ್‌ಐಆರ್ ಹುಡುಕಿ...",
    "Multi-hop linkage analysis using Neo4j": "ನಿಯೋ4ಜೆ ಬಳಸಿಕೊಂಡು ಮಲ್ಟಿ-ಹಾಪ್ ಲಿಂಕೇಜ್ ವಿಶ್ಲೇಷಣೆ",
    "Co-offender Network": "ಸಹ-ಅಪರಾಧಿಗಳ ನೆಟ್‌ವರ್ಕ್",
    "Financial Money Trail": "ಹಣಕಾಸಿನ ಹಣದ ಜಾಡು",
    "Profile": "ಪ್ರೊಫೈಲ್",
    "Status: Known Offender": "ಸ್ಥಿತಿ: ತಿಳಿದಿರುವ ಅಪರಾಧಿ",
    "RISK SCORE": "ಅಪಾಯದ ಅಂಕ",
    "Deepfake Forensics Engine": "ಡೀಪ್‌ಫೇಕ್ ಫೋರೆನ್ಸಿಕ್ಸ್ ಎಂಜಿನ್",
    "Real-Time Synthetic Audio & Voice Cloning Detection": "ನೈಜ-ಸಮಯದ ಸಿಂಥೆಟಿಕ್ ಆಡಿಯೋ ಮತ್ತು ವಾಯ್ಸ್ ಕ್ಲೋನಿಂಗ್ ಪತ್ತೆ",
    "Biometric Identification Terminal": "ಬಯೋಮೆಟ್ರಿಕ್ ಗುರುತಿನ ಟರ್ಮಿನಲ್",
    "Cross-referencing facial landmarks against national criminal databases.": "ರಾಷ್ಟ್ರೀಯ ಕ್ರಿಮಿನಲ್ ಡೇಟಾಬೇಸ್‌ಗಳ ವಿರುದ್ಧ ಮುಖದ ಹೆಗ್ಗುರುತುಗಳನ್ನು ಕ್ರಾಸ್-ರೆಫರೆನ್ಸ್ ಮಾಡಲಾಗುತ್ತಿದೆ.",
    "Predictive Spatial Dispatch": "ಮುನ್ಸೂಚಕ ಪ್ರಾದೇಶಿಕ ರವಾನೆ",
    "Real-time DBSCAN Hotspot Clustering & Dynamic Patrol Routing": "ನೈಜ-ಸಮಯದ DBSCAN ಹಾಟ್‌ಸ್ಪಾಟ್ ಕ್ಲಸ್ಟರಿಂಗ್ ಮತ್ತು ಡೈನಾಮಿಕ್ ಪೆಟ್ರೋಲ್ ರೂಟಿಂಗ್",
    "Update Matrix": "ಮ್ಯಾಟ್ರಿಕ್ಸ್ ನವೀಕರಿಸಿ",
    "Auto-Dispatch Units": "ಸ್ವಯಂ-ರವಾನೆ ಘಟಕಗಳು",
    "AI Target Overlay": "AI ಗುರಿ ಓವರ್‌ಲೇ",
    "Displaying predicted crime geometries for Bangalore Central. Evaluated via Python Pattern Engine.": "ಬೆಂಗಳೂರು ಸೆಂಟ್ರಲ್‌ಗಾಗಿ ಊಹಿಸಲಾದ ಅಪರಾಧ ರೇಖಾಗಣಿತಗಳನ್ನು ಪ್ರದರ್ಶಿಸಲಾಗುತ್ತಿದೆ. ಪೈಥಾನ್ ಪ್ಯಾಟರ್ನ್ ಎಂಜಿನ್ ಮೂಲಕ ಮೌಲ್ಯಮಾಪನ ಮಾಡಲಾಗಿದೆ.",
    "Active AI Hotspots": "ಸಕ್ರಿಯ AI ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು",
    "RISK": "ಅಪಾಯ",
    "DISPATCH UNIT": "ಘಟಕವನ್ನು ರವಾನಿಸಿ",
    "Fetching spatial matrix...": "ಪ್ರಾದೇಶಿಕ ಮ್ಯಾಟ್ರಿಕ್ಸ್ ಪಡೆಯಲಾಗುತ್ತಿದೆ...",
    "DRONE-01 : LIVE REC": "ಡ್ರೋನ್-01 : ಲೈವ್ ರೆಕಾರ್ಡಿಂಗ್",
    "BATT": "ಬ್ಯಾಟರಿ",
    "EST": "ಅಂದಾಜು",
    "SIGNAL: STRONG": "ಸಿಗ್ನಲ್: ಪ್ರಬಲ",
    "KSP AERIAL COMMAND": "ಕೆಎಸ್‌ಪಿ ಏರಿಯಲ್ ಕಮಾಂಡ್",
    "LAT:": "ಅಕ್ಷಾಂಶ:",
    "LNG:": "ರೇಖಾಂಶ:",
    "SYS TIME:": "ಸಿಸ್ಟಮ್ ಸಮಯ:",
    "LOCK ACQUIRED": "ಲಾಕ್ ಪಡೆಯಲಾಗಿದೆ",
    "VEHICLE MATCH:": "ವಾಹನ ಹೊಂದಾಣಿಕೆ:",
    "PL:": "ಪ್ಲೇಟ್:",
    "ALTITUDE": "ಎತ್ತರ",
    "AIRSPEED": "ವಾಯುವೇಗ",
    "HDG": "ಶಿಖರ",
    "TACTICAL FEEDBACK": "ಯುದ್ಧತಂತ್ರದ ಪ್ರತಿಕ್ರಿಯೆ",
    "Target isolated within DBSCAN hotspot radius. Engaging auto-tracking mode. Ground units notified.": "DBSCAN ಹಾಟ್‌ಸ್ಪಾಟ್ ತ್ರಿಜ್ಯದೊಳಗೆ ಗುರಿಯನ್ನು ಪ್ರತ್ಯೇಕಿಸಲಾಗಿದೆ. ಸ್ವಯಂ-ಟ್ರ್ಯಾಕಿಂಗ್ ಮೋಡ್ ತೊಡಗಿಸಿಕೊಳ್ಳುತ್ತಿದೆ. ನೆಲದ ಘಟಕಗಳಿಗೆ ಸೂಚಿಸಲಾಗಿದೆ.",
    "Scanning designated coordinates... Grid search active. Pattern Engine nominal.": "ಗೊತ್ತುಪಡಿಸಿದ ನಿರ್ದೇಶಾಂಕಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಲಾಗುತ್ತಿದೆ... ಗ್ರಿಡ್ ಹುಡುಕಾಟ ಸಕ್ರಿಯವಾಗಿದೆ. ಪ್ಯಾಟರ್ನ್ ಎಂಜಿನ್ ನಾಮಮಾತ್ರ.",
    "Global Cyber-Threat Operations": "ಜಾಗತಿಕ ಸೈಬರ್-ಬೆದರಿಕೆ ಕಾರ್ಯಾಚರಣೆಗಳು",
    "LIVE OSINT & DARK WEB MONITORING (CLASSIFIED)": "ಲೈವ್ ಓಸಿಂಟ್ ಮತ್ತು ಡಾರ್ಕ್ ವೆಬ್ ಮಾನಿಟರಿಂಗ್ (ವರ್ಗೀಕೃತ)",
    "BLOCKED THREATS": "ನಿರ್ಬಂಧಿಸಲಾದ ಬೆದರಿಕೆಗಳು",
    "DEFCON LEVEL": "ಡೆಫ್ಕಾನ್ ಮಟ್ಟ",
    "NODE STATUS": "ನೋಡ್ ಸ್ಥಿತಿ",
    "SECURE": "ಸುರಕ್ಷಿತ",
    "SENSOR ARRAY 04": "ಸಂವೇದಕ ರಚನೆ 04",
    "MONITORING BENGALURU METRO GRID": "ಬೆಂಗಳೂರು ಮೆಟ್ರೋ ಗ್ರಿಡ್ ಮಾನಿಟರಿಂಗ್",
    "LIVE THREAT LOG": "ಲೈವ್ ಬೆದರಿಕೆ ಲಾಗ್",
    "Automated LLM Legal Drafter": "ಸ್ವಯಂಚಾಲಿತ LLM ಕಾನೂನು ಕರಡುಗಾರ",
    "One-click generation of court-ready Warrants and Subpoenas via AI.": "AI ಮೂಲಕ ನ್ಯಾಯಾಲಯಕ್ಕೆ-ಸಿದ್ಧವಾಗಿರುವ ವಾರಂಟ್‌ಗಳು ಮತ್ತು ಸಬ್‌ಪೋನಾಗಳ ಒಂದು ಕ್ಲಿಕ್ ಉತ್ಪಾದನೆ.",
    "Draft Parameters": "ಕರಡು ನಿಯತಾಂಕಗಳು",
    "Target Suspect ID": "ಗುರಿ ಶಂಕಿತ ID",
    "Case Type / Allegation": "ಪ್ರಕರಣದ ಪ್ರಕಾರ / ಆರೋಪ",
    "LLM DRAFTING...": "LLM ಕರಡು ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    "GENERATE WARRANT": "ವಾರಂಟ್ ರಚಿಸಿ",
    "EXPORT TO PDF": "PDF ಗೆ ರಫ್ತು ಮಾಡಿ",
    "AWAITING AI DRAFT": "AI ಕರಡುಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ",
    "CELLULAR AUTOPSY": "ಸೆಲ್ಯುಲರ್ ಶವಪರೀಕ್ಷೆ",
    "NANOBOT SWARM DIAGNOSTICS": "ನ್ಯಾನೊಬಾಟ್ ಸ್ವಾರ್ಮ್ ಡಯಾಗ್ನೋಸ್ಟಿಕ್ಸ್",
    "SUBJECT ID": "ವಿಷಯದ ID",
    "INJECT SWARM": "ಸ್ವಾರ್ಮ್ ಅನ್ನು ಚುಚ್ಚಿ",
    "AWAITING INJECTION": "ಇಂಜೆಕ್ಷನ್‌ಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ",
    "SYNTHETIC PATHOGEN DETECTED": "ಸಿಂಥೆಟಿಕ್ ರೋಗಕಾರಕ ಪತ್ತೆಯಾಗಿದೆ",
    "CAUSE OF DEATH: NANO-TOXICITY": "ಸಾವಿಗೆ ಕಾರಣ: ನ್ಯಾನೊ-ಟಾಕ್ಸಿಸಿಟಿ",
    "SWARM TELEMETRY": "ಸ್ವಾರ್ಮ್ ಟೆಲಿಮೆಟ್ರಿ",
    "ACTIVE BOTS": "ಸಕ್ರಿಯ ಬಾಟ್‌ಗಳು",
    "COVERAGE": "ವ್ಯಾಪ್ತಿ",
    "CELLULAR INTEGRITY": "ಸೆಲ್ಯುಲರ್ ಸಮಗ್ರತೆ",
    "COMPROMISED": "ರಾಜಿಯಾಗಿದೆ",
    "NOMINAL": "ನಾಮಮಾತ್ರ",
    "ANOMALY LOG": "ಅಸಂಗತ ಲಾಗ್",
    "ORBITAL COMMAND": "ಕಕ್ಷೆಯ ಕಮಾಂಡ್",
    "LEO SATELLITE UPLINK: SAT-V IND-01": "LEO ಉಪಗ್ರಹ ಅಪ್‌ಲಿಂಕ್: SAT-V IND-01",
    "ALTITUDE: 400KM": "ಎತ್ತರ: 400KM",
    "VELOCITY: 7.66 KM/S": "ವೇಗ: 7.66 KM/S",
    "ENGAGE TARGET LOCK": "ಗುರಿ ಲಾಕ್ ಅನ್ನು ತೊಡಗಿಸಿಕೊಳ್ಳಿ",
    "TRK: ACTIVE": "ಟ್ರ್ಯಾಕಿಂಗ್: ಸಕ್ರಿಯ",
    "THERMAL ON": "ಥರ್ಮಲ್ ಆನ್",
    "GYRO: STABLE": "ಗೈರೊ: ಸ್ಥಿರ",
    "HIGH VALUE TARGET": "ಹೆಚ್ಚಿನ ಮೌಲ್ಯದ ಗುರಿ",
    "ISRO COMMAND LINK: ENCRYPTED": "ಇಸ್ರೋ ಕಮಾಂಡ್ ಲಿಂಕ್: ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ",
    "SMART GRID C2": "ಸ್ಮಾರ್ಟ್ ಗ್ರಿಡ್ C2",
    "CITY-WIDE INFRASTRUCTURE OVERRIDE": "ನಗರ-ವ್ಯಾಪಿ ಮೂಲಸೌಕರ್ಯ ಅತಿಕ್ರಮಣ",
    "PROTOCOL: GHOST-NET": "ಪ್ರೋಟೋಕಾಲ್: ಘೋಸ್ಟ್-ನೆಟ್",
    "ACTIVE OVERRIDE": "ಸಕ್ರಿಯ ಅತಿಕ್ರಮಣ",
    "RELEASE GRID": "ಗ್ರಿಡ್ ಅನ್ನು ಬಿಡುಗಡೆ ಮಾಡಿ",
    "TACTICAL OVERRIDE ENGAGED": "ಯುದ್ಧತಂತ್ರದ ಅತಿಕ್ರಮಣ ತೊಡಗಿಸಿಕೊಂಡಿದೆ",
    "SMART INFRASTRUCTURE HIJACKED. SUSPECT CONTAINED.": "ಸ್ಮಾರ್ಟ್ ಮೂಲಸೌಕರ್ಯ ಅಪಹರಿಸಲಾಗಿದೆ. ಶಂಕಿತನನ್ನು ಬಂಧಿಸಲಾಗಿದೆ.",
    "SELECT SECTOR FOR OVERRIDE": "ಅತಿಕ್ರಮಣಕ್ಕಾಗಿ ವಲಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "WARNING: THIS ACTION MANIPULATES PHYSICAL CITY INFRASTRUCTURE": "ಎಚ್ಚರಿಕೆ: ಈ ಕ್ರಿಯೆಯು ಭೌತಿಕ ನಗರದ ಮೂಲಸೌಕರ್ಯವನ್ನು ನಿರ್ವಹಿಸುತ್ತದೆ",
    "HIJACKED": "ಅಪಹರಿಸಲಾಗಿದೆ",
    "Policy & Audit Control Panel": "ನೀತಿ ಮತ್ತು ಆಡಿಟ್ ನಿಯಂತ್ರಣ ಫಲಕ",
    "Configure security layers, audit trails, and automated thresholds": "ಭದ್ರತಾ ಲೇಯರ್‌ಗಳು, ಆಡಿಟ್ ಟ್ರೇಲ್ಸ್ ಮತ್ತು ಸ್ವಯಂಚಾಲಿತ ಮಿತಿಗಳನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಿ",
    "Refresh State": "ಸ್ಥಿತಿಯನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ",
    "Cryptographic Audit Trail": "ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಆಡಿಟ್ ಟ್ರಯಲ್",
    "Alert Rule Policies": "ಎಚ್ಚರಿಕೆ ನಿಯಮ ನೀತಿಗಳು",
    "Role Access Control": "ಪಾತ್ರ ಪ್ರವೇಶ ನಿಯಂತ್ರಣ",
    "Tamper Simulator": "ಟ್ಯಾಂಪರ್ ಸಿಮ್ಯುಲೇಟರ್",
    "Tamper-Proof Audit logs": "ಟ್ಯಾಂಪರ್-ಪ್ರೂಫ್ ಆಡಿಟ್ ಲಾಗ್‌ಗಳು",
    "SHA-256 Validation Active": "SHA-256 ಮೌಲ್ಯೀಕರಣ ಸಕ್ರಿಯವಾಗಿದೆ",
    "Timestamp": "ಸಮಯಮುದ್ರೆ",
    "User": "ಬಳಕೆದಾರ",
    "Action": "ಕ್ರಿಯೆ",
    "IP Address": "ಐಪಿ ವಿಳಾಸ",
    "Query Details": "ಪ್ರಶ್ನೆ ವಿವರಗಳು",
    "Cryptographic Integrity": "ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಸಮಗ್ರತೆ",
    "TAMPERED / INVALID SIGNATURE": "ಟ್ಯಾಂಪರ್ಡ್ / ಅಮಾನ್ಯ ಸಹಿ",
    "VERIFIED HASH": "ಪರಿಶೀಲಿಸಿದ ಹ್ಯಾಶ್",
    "Define New Alert Threshold": "ಹೊಸ ಎಚ್ಚರಿಕೆ ಮಿತಿಯನ್ನು ವಿವರಿಸಿ",
    "Rule Type": "ನಿಯಮದ ಪ್ರಕಾರ",
    "Condition Expression": "ಷರತ್ತು ಅಭಿವ್ಯಕ್ತಿ",
    "Add Rule to Alert Engine": "ಅಲರ್ಟ್ ಎಂಜಿನ್‌ಗೆ ನಿಯಮವನ್ನು ಸೇರಿಸಿ",
    "Active System Monitoring Rules": "ಸಕ್ರಿಯ ಸಿಸ್ಟಮ್ ಮಾನಿಟರಿಂಗ್ ನಿಯಮಗಳು",
    "ACTIVE MONITORING": "ಸಕ್ರಿಯ ಮಾನಿಟರಿಂಗ್",
    "Map Officer Role": "ನಕ್ಷೆ ಅಧಿಕಾರಿ ಪಾತ್ರ",
    "Officer Email": "ಅಧಿಕಾರಿಯ ಇಮೇಲ್",
    "RBAC Role": "RBAC ಪಾತ್ರ",
    "Division / Unit": "ವಿಭಾಗ / ಘಟಕ",
    "Assign Role": "ಪಾತ್ರವನ್ನು ನಿಯೋಜಿಸಿ",
    "Keycloak Mapped Officers & Roles": "ಕೀಕ್ಲೋಕ್ ಮ್ಯಾಪ್ ಮಾಡಿದ ಅಧಿಕಾರಿಗಳು ಮತ್ತು ಪಾತ್ರಗಳು",
    "Assigned Role": "ನಿಯೋಜಿತ ಪಾತ್ರ",
    "Division": "ವಿಭಾಗ",
    "Actions": "ಕ್ರಿಯೆಗಳು",
    "Cryptographic Tamper Simulator": "ಕ್ರಿಪ್ಟೋಗ್ರಾಫಿಕ್ ಟ್ಯಾಂಪರ್ ಸಿಮ್ಯುಲೇಟರ್",
    "Every query executed on the NEXUS-KSP engine computes a strict SHA-256 HMAC of the (query + response payload), signed at the database interface. If any record is mutated by a hacker or rogue script directly inside the database, the signature verification check will fail.": "NEXUS-KSP ಎಂಜಿನ್‌ನಲ್ಲಿ ಕಾರ್ಯಗತಗೊಳಿಸಲಾದ ಪ್ರತಿಯೊಂದು ಪ್ರಶ್ನೆಯು (ಕ್ವೆರಿ + ರೆಸ್ಪಾನ್ಸ್ ಪೇಲೋಡ್) ನ ಕಟ್ಟುನಿಟ್ಟಾದ SHA-256 HMAC ಅನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡುತ್ತದೆ, ಇದನ್ನು ಡೇಟಾಬೇಸ್ ಇಂಟರ್‌ಫೇಸ್‌ನಲ್ಲಿ ಸಹಿ ಮಾಡಲಾಗಿದೆ. ಯಾವುದೇ ರೆಕಾರ್ಡ್ ಅನ್ನು ಹ್ಯಾಕರ್ ಅಥವಾ ರೋಗ್ ಸ್ಕ್ರಿಪ್ಟ್ ನೇರವಾಗಿ ಡೇಟಾಬೇಸ್ ಒಳಗೆ ರೂಪಾಂತರಿಸಿದರೆ, ಸಹಿ ಪರಿಶೀಲನೆ ಚೆಕ್ ವಿಫಲಗೊಳ್ಳುತ್ತದೆ.",
    "Click below to inject simulated database corruption to show how the audit trail catches mutations in real-time.": "ನೈಜ ಸಮಯದಲ್ಲಿ ಆಡಿಟ್ ಟ್ರೇಲ್ ರೂಪಾಂತರಗಳನ್ನು ಹೇಗೆ ಹಿಡಿಯುತ್ತದೆ ಎಂಬುದನ್ನು ತೋರಿಸಲು ಸಿಮ್ಯುಲೇಟೆಡ್ ಡೇಟಾಬೇಸ್ ಭ್ರಷ್ಟಾಚಾರವನ್ನು ಚುಚ್ಚಲು ಕೆಳಗೆ ಕ್ಲಿಕ್ ಮಾಡಿ.",
    "Reset Logs (Fix Database Integrity)": "ಲಾಗ್‌ಗಳನ್ನು ಮರುಹೊಂದಿಸಿ (ಡೇಟಾಬೇಸ್ ಸಮಗ್ರತೆಯನ್ನು ಸರಿಪಡಿಸಿ)",
    "Simulate Database SQL Mutation (Tampering)": "ಡೇಟಾಬೇಸ್ SQL ರೂಪಾಂತರವನ್ನು ಅನುಕರಿಸಿ (ಟ್ಯಾಂಪರಿಂಗ್)",
    "CRITICAL SYSTEM THREAT:": "ನಿರ್ಣಾಯಕ ಸಿಸ್ಟಮ್ ಬೆದರಿಕೆ:",
    "A query in Row #1 was altered in the Postgres logs, but its SHA-256 integrity hash remains mismatched. The audit engine flagged this mutation instantly!": "ಸಾಲು #1 ರ ಪ್ರಶ್ನೆಯನ್ನು ಪೋಸ್ಟ್‌ಗ್ರೆಸ್ ಲಾಗ್‌ಗಳಲ್ಲಿ ಬದಲಾಯಿಸಲಾಗಿದೆ, ಆದರೆ ಅದರ SHA-256 ಸಮಗ್ರತೆಯ ಹ್ಯಾಶ್ ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ. ಆಡಿಟ್ ಇಂಜಿನ್ ತಕ್ಷಣ ಈ ರೂಪಾಂತರವನ್ನು ಫ್ಲ್ಯಾಗ್ ಮಾಡಿದೆ!",
    "AI Suspect Interrogation Simulator": "AI ಶಂಕಿತ ವಿಚಾರಣೆಯ ಸಿಮ್ಯುಲೇಟರ್",
    "PSYCHOLOGICAL AVATAR MODULE: ACC-8091 (Ravi Kumar)": "ಮಾನಸಿಕ ಅವತಾರ ಮಾಡ್ಯೂಲ್: ACC-8091 (ರವಿ ಕುಮಾರ್)",
    "AVATAR STATUS": "ಅವತಾರ ಸ್ಥಿತಿ",
    "AGGRESSION THRESHOLD: HIGH": "ಆಕ್ರಮಣಶೀಲತೆಯ ಮಿತಿ: ಹೆಚ್ಚು",
    "INTERROGATION TRANSCRIPT": "ವಿಚಾರಣೆಯ ಪ್ರತಿಲಿಪಿ",
    "INITIATE QUESTIONING SEQUENCE": "ಪ್ರಶ್ನಿಸುವ ಅನುಕ್ರಮವನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    "INVESTIGATOR": "ತನಿಖಾಧಿಕಾರಿ",
    "SUSPECT AVATAR": "ಶಂಕಿತ ಅವತಾರ",
    "Analyzing psychological parameters...": "ಮಾನಸಿಕ ನಿಯತಾಂಕಗಳನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    "INTERROGATE": "ವಿಚಾರಣೆ ನಡೆಸಿ",
    "BIOMETRIC TELEMETRY": "ಬಯೋಮೆಟ್ರಿಕ್ ಟೆಲಿಮೆಟ್ರಿ",
    "CORTISOL / STRESS": "ಕಾರ್ಟಿಸೋಲ್ / ಒತ್ತಡ",
    "DECEPTION PROBABILITY": "ವಂಚನೆ ಸಂಭವನೀಯತೆ",
    "VOCAL TENSION FREQUENCY": "ಗಾಯನ ಟೆನ್ಶನ್ ಆವರ್ತನ",
    "CYBERNETIC REHABILITATION": "ಸೈಬರ್ನೆಟಿಕ್ ಪುನರ್ವಸತಿ",
    "NEURAL PATHWAY OVERWRITE PROTOCOL": "ನ್ಯೂರಲ್ ಪಾಥ್‌ವೇ ಓವರ್‌ರೈಟ್ ಪ್ರೋಟೋಕಾಲ್",
    "RECIDIVISM PROBABILITY": "ಮರುಕಳಿಸುವಿಕೆಯ ಸಂಭವನೀಯತೆ",
    "SUBJECT REHABILITATED": "ವಿಷಯವನ್ನು ಪುನರ್ವಸತಿ ಮಾಡಲಾಗಿದೆ",
    "SOCIETAL REINTEGRATION APPROVED": "ಸಾಮಾಜಿಕ ಮರುಸೇರ್ಪಡೆ ಅನುಮೋದಿಸಲಾಗಿದೆ",
    "TARGET PATHWAYS": "ಗುರಿ ಮಾರ್ಗಗಳು",
    "SYNTHETIC OVERRIDE": "ಸಿಂಥೆಟಿಕ್ ಅತಿಕ್ರಮಣ",
    "NATURAL (HOSTILE)": "ನೈಸರ್ಗಿಕ (ಪ್ರತಿಕೂಲ)",
    "OVERWRITING [": "ತಿದ್ದಿ ಬರೆಯಲಾಗುತ್ತಿದೆ [",
    "SEQUENCE COMPLETE": "ಅನುಕ್ರಮ ಪೂರ್ಣಗೊಂಡಿದೆ",
    "COMMENCE NEURAL REWRITE": "ನ್ಯೂರಲ್ ಪುನರಾವರ್ತನೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ",
    "CHRONOS MODULE": "ಕ್ರೊನೊಸ್ ಮಾಡ್ಯೂಲ್",
    "AMBIENT TEMPORAL RECONSTRUCTION": "ಆಂಬಿಯೆಂಟ್ ಟೆಂಪೊರಲ್ ರಿಕನ್ಸ್ಟ್ರಕ್ಷನ್",
    "SCENE LOCK: SECTOR 4": "ಸೀನ್ ಲಾಕ್: ಸೆಕ್ಟರ್ 4",
    "T-MINUS:": "ಟಿ-ಮೈನಸ್:",
    "SECONDS": "ಸೆಕೆಂಡುಗಳು",
    "T-MINUS 100s": "ಟಿ-ಮೈನಸ್ 100s",
    "CURRENT:": "ಪ್ರಸ್ತುತ:",
    "EVENT START (0s)": "ಈವೆಂಟ್ ಪ್ರಾರಂಭ (0s)",
    "Real-Time AI Surveillance": "ನೈಜ-ಸಮಯದ AI ಕಣ್ಗಾವಲು",
    "Automated Object Tracking & Anomaly Detection": "ಸ್ವಯಂಚಾಲಿತ ವಸ್ತು ಟ್ರ್ಯಾಕಿಂಗ್ ಮತ್ತು ಅಸಂಗತ ಪತ್ತೆ",
    "SYSTEM ACTIVE": "ಸಿಸ್ಟಮ್ ಸಕ್ರಿಯವಾಗಿದೆ",
    "ANOMALY DETECTIONS": "ಅಸಂಗತ ಪತ್ತೆಗಳು",
    "Monitoring feeds...": "ಫೀಡ್‌ಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಲಾಗುತ್ತಿದೆ..."
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    const stored = localStorage.getItem('nexus_lang');
    if (stored === 'en' || stored === 'kn') {
      setLanguage(stored as Language);
    }
  }, []);

  const changeLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('nexus_lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
